// Generado por tools/gen_catalog.py a partir de docs/juegos/*.md. No editar a mano.
import { SPEC, type Categoria, type ScoreSpec } from '@playzoo/shared';

export type Fiabilidad = 'oficial' | 'video' | 'video+analisis' | 'sin confirmar';

export interface GameMeta {
  id: string;
  num: number;
  nombre: string;
  emoji: string;
  categoria: Categoria;
  marcador: ScoreSpec;
  top1: number | null;
  duracionSeg: number;
  instrucciones: string;
  fiabilidad: Fiabilidad;
  kit: string;
  tamano: 'S' | 'M' | 'L';
  ola: 'A' | 'B' | 'C' | 'D' | 'E';
}

export const CATALOG: GameMeta[] = [
  { id: "pinguino-escalador", num: 1, nombre: "Pingüino Escalador", emoji: "🐧", categoria: 'habilidad', marcador: SPEC.metros, top1: 163.9, duracionSeg: 60, instrucciones: "Toca en el momento justo para soltarte del piolet y volar hasta la zona verde del siguiente hielo. Un aterrizaje perfecto da +10 m.", fiabilidad: 'oficial', kit: 'orbit-anchor', tamano: 'M', ola: 'D' },
  { id: "puas-de-puercoespin", num: 2, nombre: "Púas de Puercoespín", emoji: "🐡", categoria: 'habilidad', marcador: SPEC.puntos, top1: 26, duracionSeg: 60, instrucciones: "Toca para disparar la púa hacia el otro lado y colarla por un hueco libre sin chocar con las púas clavadas.", fiabilidad: 'video', kit: 'tap-timing', tamano: 'S', ola: 'C' },
  { id: "lemur-giratorio", num: 3, nombre: "Lémur Giratorio", emoji: "🐒", categoria: 'habilidad', marcador: SPEC.puntos, top1: 114, duracionSeg: 60, instrucciones: "Engánchate al ancla solo cuando la bola esté en la zona roja. Suelta cuando apunte recta al siguiente tramo.", fiabilidad: 'video+analisis', kit: 'orbit-anchor', tamano: 'M', ola: 'D' },
  { id: "libelula-espacial", num: 4, nombre: "Libélula Espacial", emoji: "🪰", categoria: 'habilidad', marcador: SPEC.puntos, top1: 61, duracionSeg: 60, instrucciones: "Arrastra el dedo para guiar la libélula entre los asteroides sin chocar.", fiabilidad: 'video', kit: 'scroller', tamano: 'S', ola: 'C' },
  { id: "armadillo-en-picado", num: 5, nombre: "Armadillo en Picado", emoji: "🐢", categoria: 'habilidad', marcador: SPEC.puntos, top1: 462, duracionSeg: 60, instrucciones: "Mantén pulsado para bajar y da toques para girar la torre. Anticípate a los huecos y evita los pisos rojos.", fiabilidad: 'video', kit: 'pseudo3d-helix', tamano: 'L', ola: 'D' },
  { id: "rana-saltarina", num: 6, nombre: "Rana Saltarina", emoji: "🐸", categoria: 'habilidad', marcador: SPEC.puntos, top1: 554, duracionSeg: 60, instrucciones: "Mantén pulsado para cargar el salto y suelta para saltar. Cae en la siguiente plataforma; centrado da puntos extra.", fiabilidad: 'video', kit: 'tap-timing', tamano: 'S', ola: 'C' },
  { id: "pulga-botadora", num: 7, nombre: "Pulga Botadora", emoji: "🐞", categoria: 'habilidad', marcador: SPEC.puntos, top1: 69, duracionSeg: 60, instrucciones: "Dibuja una línea bajo la pulga para que rebote y no caiga a los pinchos. Los rebotes seguidos dan combos.", fiabilidad: 'video+analisis', kit: 'physics-lite', tamano: 'M', ola: 'C' },
  { id: "gallina-aleteadora", num: 8, nombre: "Gallina Aleteadora", emoji: "🐔", categoria: 'habilidad', marcador: SPEC.metros, top1: 190, duracionSeg: 60, instrucciones: "Toca a la izquierda o a la derecha para aletear hacia ese lado. Sube por el desfiladero sin tocar las paredes; ojo al viento.", fiabilidad: 'oficial', kit: 'scroller', tamano: 'M', ola: 'C' },
  { id: "murcielago-entre-pinchos", num: 9, nombre: "Murciélago entre Pinchos", emoji: "🦇", categoria: 'habilidad', marcador: SPEC.puntos, top1: 42, duracionSeg: 60, instrucciones: "El murciélago rebota de pared a pared. Toca para aletear y cambiar de sentido esquivando los pinchos.", fiabilidad: 'video', kit: 'scroller', tamano: 'S', ola: 'C' },
  { id: "guepardo-derrapante", num: 10, nombre: "Guepardo Derrapante", emoji: "🐆", categoria: 'habilidad', marcador: SPEC.puntos, top1: 143, duracionSeg: 60, instrucciones: "Toca para girar en cada curva del camino sin salirte.", fiabilidad: 'video', kit: 'path-follow', tamano: 'S', ola: 'C' },
  { id: "gorrion-aleteador", num: 11, nombre: "Gorrión Aleteador", emoji: "🐦", categoria: 'habilidad', marcador: SPEC.puntos, top1: 30, duracionSeg: 60, instrucciones: "Cada toque impulsa al gorrión hacia arriba. Pasa por los huecos entre columnas sin tocarlas.", fiabilidad: 'video', kit: 'scroller', tamano: 'S', ola: 'C' },
  { id: "abejorro-propulsado", num: 12, nombre: "Abejorro Propulsado", emoji: "🐝", categoria: 'habilidad', marcador: SPEC.metros, top1: 264, duracionSeg: 60, instrucciones: "Arrastra a izquierda y derecha para subir esquivando los rayos láser. Fíjate en los avisos.", fiabilidad: 'video+analisis', kit: 'scroller', tamano: 'M', ola: 'C' },
  { id: "erizo-cruzacalles", num: 13, nombre: "Erizo Cruzacalles", emoji: "🦔", categoria: 'habilidad', marcador: SPEC.puntos, top1: 124, duracionSeg: 40, instrucciones: "Desliza arriba, abajo, izquierda o derecha para cruzar los carriles esquivando coches. No te quedes parado.", fiabilidad: 'oficial', kit: 'lane-cross', tamano: 'S', ola: 'C' },
  { id: "foca-malabarista", num: 14, nombre: "Foca Malabarista", emoji: "🦭", categoria: 'habilidad', marcador: SPEC.puntos, top1: 41, duracionSeg: 60, instrucciones: "Mantén pulsado y arrastra para que la pelota no caiga. Cada toque suma un punto.", fiabilidad: 'oficial', kit: 'physics-lite', tamano: 'S', ola: 'C' },
  { id: "castor-lanzador", num: 15, nombre: "Castor Lanzador", emoji: "🦫", categoria: 'habilidad', marcador: SPEC.puntos, top1: 54, duracionSeg: 60, instrucciones: "Toca para lanzar un diente al tronco que gira. No des a los que ya están clavados.", fiabilidad: 'video', kit: 'tap-timing', tamano: 'S', ola: 'C' },
  { id: "liebre-en-la-autopista", num: 16, nombre: "Liebre en la Autopista", emoji: "🐇", categoria: 'habilidad', marcador: SPEC.metros0, top1: 1026, duracionSeg: 60, instrucciones: "Toca a izquierda o derecha para cambiar de carril y esquivar el tráfico. La velocidad aumenta.", fiabilidad: 'video', kit: 'lane-cross', tamano: 'S', ola: 'C' },
  { id: "lobo-lunar", num: 17, nombre: "Lobo Lunar", emoji: "🐺", categoria: 'habilidad', marcador: SPEC.metros2, top1: 91.76, duracionSeg: 60, instrucciones: "Toca para fijar el ángulo del lanzamiento y mantén pulsado en las bajadas para ganar velocidad. Un buen ángulo es Perfecto y congela el reloj.", fiabilidad: 'video+analisis', kit: 'physics-lite', tamano: 'M', ola: 'D' },
  { id: "panda-lenador", num: 18, nombre: "Panda Leñador", emoji: "🐼", categoria: 'habilidad', marcador: SPEC.puntos, top1: 130, duracionSeg: 60, instrucciones: "Toca a izquierda o derecha para cortar el bambú cambiando de lado y esquivar las ramas antes de que se vacíe el tiempo.", fiabilidad: 'video', kit: 'tap-timing', tamano: 'S', ola: 'C' },
  { id: "gecko-trepador", num: 19, nombre: "Gecko Trepador", emoji: "🦎", categoria: 'habilidad', marcador: SPEC.metros, top1: 76.8, duracionSeg: 60, instrucciones: "Toca para saltar de pared a pared evitando los pinchos.", fiabilidad: 'video', kit: 'scroller', tamano: 'S', ola: 'C' },
  { id: "anguila-electrica", num: 20, nombre: "Anguila Eléctrica", emoji: "🐟", categoria: 'habilidad', marcador: SPEC.puntos, top1: 113, duracionSeg: 60, instrucciones: "Toca para cambiar de dirección. Avanza en zigzag entre las barras de neón y recoge los puntos amarillos.", fiabilidad: 'oficial', kit: 'path-follow', tamano: 'S', ola: 'C' },
  { id: "mantis-cortadora", num: 21, nombre: "Mantis Cortadora", emoji: "🦂", categoria: 'habilidad', marcador: SPEC.puntos, top1: 306, duracionSeg: 60, instrucciones: "Mantén pulsado para cortar cubos seguidos y levanta el dedo antes de los prohibidos. Tienes 3 vidas.", fiabilidad: 'video+analisis', kit: 'slice-hold', tamano: 'M', ola: 'D' },
  { id: "serpiente-glotona", num: 22, nombre: "Serpiente Glotona", emoji: "🐍", categoria: 'habilidad', marcador: SPEC.puntos, top1: 25, duracionSeg: 60, instrucciones: "Desliza para dirigir la serpiente. Cada fruta alarga la cola y sube la velocidad. Esquiva los obstáculos.", fiabilidad: 'oficial', kit: 'grid-snake', tamano: 'S', ola: 'C' },
  { id: "flamenco-equilibrista", num: 23, nombre: "Flamenco Equilibrista", emoji: "🦩", categoria: 'habilidad', marcador: SPEC.segundosMas, top1: 33.59, duracionSeg: 60, instrucciones: "Mueve el dedo a los lados para mantener la espada en equilibrio. Aguanta todo lo que puedas.", fiabilidad: 'oficial', kit: 'balance', tamano: 'M', ola: 'C' },
  { id: "arana-tejedora", num: 24, nombre: "Araña Tejedora", emoji: "🕷️", categoria: 'habilidad', marcador: SPEC.puntos, top1: 163, duracionSeg: 60, instrucciones: "Dos botones: uno gira el hilo y otro lo hace crecer. Ve de nodo en nodo sin romper el hilo.", fiabilidad: 'video+analisis', kit: 'orbit-anchor', tamano: 'M', ola: 'D' },
  { id: "tucan-balancin", num: 25, nombre: "Tucán Balancín", emoji: "🐦", categoria: 'habilidad', marcador: SPEC.segundosMas, top1: 63.87, duracionSeg: 60, instrucciones: "Toca a izquierda o derecha para inclinar la balanza y mantener la bola. Centrada da \"Perfecto (2x)\".", fiabilidad: 'video', kit: 'balance', tamano: 'S', ola: 'C' },
  { id: "camaleon-columpio", num: 26, nombre: "Camaleón Columpio", emoji: "🦎", categoria: 'habilidad', marcador: SPEC.puntos, top1: 310, duracionSeg: 60, instrucciones: "Mantén pulsado para engancharte con la lengua y suelta para volar entre columnas.", fiabilidad: 'oficial', kit: 'orbit-anchor', tamano: 'M', ola: 'D' },
  { id: "canguro-trampolin", num: 27, nombre: "Canguro Trampolín", emoji: "🦘", categoria: 'habilidad', marcador: SPEC.puntos, top1: 176, duracionSeg: 60, instrucciones: "El canguro rebota solo. Arrastra a los lados para caer en las plataformas y subir sin caerte.", fiabilidad: 'video', kit: 'scroller', tamano: 'S', ola: 'C' },
  { id: "hormiga-zigzag", num: 28, nombre: "Hormiga Zigzag", emoji: "🐜", categoria: 'habilidad', marcador: SPEC.puntos, top1: 201, duracionSeg: 60, instrucciones: "Toca para cambiar de dirección y que la hormiga no se caiga del camino en zigzag.", fiabilidad: 'oficial', kit: 'path-follow', tamano: 'S', ola: 'C' },
  { id: "ojo-de-halcon", num: 29, nombre: "Ojo de Halcón", emoji: "🦅", categoria: 'precision', marcador: SPEC.precision, top1: 97.89, duracionSeg: 30, instrucciones: "Una aguja recorre una barra de colores: toca cuando esté en el centro. Son 5 toques.", fiabilidad: 'oficial', kit: 'tap-timing', tamano: 'S', ola: 'A' },
  { id: "medusa-a-partes-iguales", num: 30, nombre: "Medusa a Partes Iguales", emoji: "🪼", categoria: 'precision', marcador: SPEC.precision, top1: 99, duracionSeg: 30, instrucciones: "Arrastra el dedo sobre la medusa para cortarla: primero por la mitad (50 %), luego un tercio y luego un cuarto.", fiabilidad: 'oficial', kit: 'geometry-cut', tamano: 'M', ola: 'D' },
  { id: "gallo-puntual", num: 31, nombre: "Gallo Puntual", emoji: "🐓", categoria: 'precision', marcador: SPEC.desviacion, top1: 0, duracionSeg: 40, instrucciones: "Un contador avanza y el gallo pide \"Toca en 7\": detenlo justo en ese valor. Son 5 rondas.", fiabilidad: 'oficial', kit: 'tap-timing', tamano: 'S', ola: 'A' },
  { id: "grillo-ritmico", num: 32, nombre: "Grillo Rítmico", emoji: "🦗", categoria: 'precision', marcador: SPEC.precision, top1: 98.4, duracionSeg: 40, instrucciones: "Primero toca siguiendo el pulso de luz. Después la luz desaparece y debes mantener el mismo tempo.", fiabilidad: 'oficial', kit: 'tap-timing', tamano: 'S', ola: 'A' },
  { id: "marmota-cronometro", num: 33, nombre: "Marmota Cronómetro", emoji: "🦫", categoria: 'precision', marcador: SPEC.desviacion, top1: 0.06, duracionSeg: 40, instrucciones: "\"Toca cuando termine\": una barra se vacía y hay que tocar justo al final. Son 3 rondas.", fiabilidad: 'oficial', kit: 'tap-timing', tamano: 'S', ola: 'A' },
  { id: "jirafa-apiladora", num: 34, nombre: "Jirafa Apiladora", emoji: "🦒", categoria: 'precision', marcador: SPEC.bloques, top1: 173, duracionSeg: 40, instrucciones: "Toca para soltar cada bloque sobre la torre. Lo que sobresale se corta y los bloques van cada vez más rápido.", fiabilidad: 'oficial', kit: 'tap-timing', tamano: 'S', ola: 'A' },
  { id: "paloma-mensajera", num: 35, nombre: "Paloma Mensajera", emoji: "🕊️", categoria: 'precision', marcador: SPEC.puntos, top1: 78, duracionSeg: 60, instrucciones: "Toca para sellar las cartas cuando estén bajo el matasellos. Centrado da \"Perfecto +2\". No selles las marcadas con X.", fiabilidad: 'video', kit: 'tap-timing', tamano: 'S', ola: 'A' },
  { id: "nutria-lanzadora", num: 36, nombre: "Nutria Lanzadora", emoji: "🦦", categoria: 'precision', marcador: SPEC.puntos, top1: 950, duracionSeg: 60, instrucciones: "Arrastra para apuntar y elegir la fuerza y suelta para lanzar a los flotadores. Cuenta con el viento. Cada acierto suma +100.", fiabilidad: 'video', kit: 'aim-throw', tamano: 'M', ola: 'D' },
  { id: "escarabajo-pelotero", num: 37, nombre: "Escarabajo Pelotero", emoji: "🪲", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 8.8, duracionSeg: 60, instrucciones: "Lleva la bola con el joystick por el circuito. Hay 2 rondas y cuenta el mejor tiempo.", fiabilidad: 'oficial', kit: 'joystick-track', tamano: 'M', ola: 'E' },
  { id: "carrera-de-galgos", num: 38, nombre: "Carrera de Galgos", emoji: "🐕", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 19.06, duracionSeg: 60, instrucciones: "Carrera de 2 vueltas. Toca la mitad izquierda o derecha para girar; salirte de la pista te frena.", fiabilidad: 'video', kit: 'racing-topdown', tamano: 'M', ola: 'E' },
  { id: "correcaminos", num: 39, nombre: "Correcaminos", emoji: "🐦", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 10.76, duracionSeg: 40, instrucciones: "Carrera de 2 vueltas con botones de izquierda, derecha y freno.", fiabilidad: 'video', kit: 'pseudo3d-racing', tamano: 'L', ola: 'E' },
  { id: "hamster-al-volante", num: 40, nombre: "Hámster al Volante", emoji: "🐹", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 15.25, duracionSeg: 60, instrucciones: "Scalextric de 3 vueltas con botones de gas y freno. Si vas demasiado rápido en una curva, la barra se pone roja y te sales.", fiabilidad: 'video', kit: 'slot-car', tamano: 'M', ola: 'E' },
  { id: "topo-golfista", num: 41, nombre: "Topo Golfista", emoji: "🦡", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 4.56, duracionSeg: 47, instrucciones: "Arrastra hacia atrás desde la bola para apuntar y elegir la potencia. Puedes golpear aunque siga en movimiento.", fiabilidad: 'oficial', kit: 'golf', tamano: 'M', ola: 'E' },
  { id: "topo-golfista-2", num: 42, nombre: "Topo Golfista 2", emoji: "🦡", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 5.78, duracionSeg: 47, instrucciones: "Igual que Topo Golfista, en un campo de minigolf en 3D.", fiabilidad: 'video', kit: 'golf', tamano: 'L', ola: 'E' },
  { id: "suricatas-del-minigolf", num: 43, nombre: "Suricatas del Minigolf", emoji: "🐾", categoria: 'velocidad', marcador: SPEC.hoyos, top1: 12.8, duracionSeg: 30, instrucciones: "Apunta, elige la potencia y emboca. Completa tantos hoyos como puedas en 30 segundos.", fiabilidad: 'oficial', kit: 'golf', tamano: 'M', ola: 'E' },
  { id: "raton-de-laberinto", num: 44, nombre: "Ratón de Laberinto", emoji: "🐭", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 12.69, duracionSeg: 60, instrucciones: "Inclina el laberinto con el joystick, llega a las 3 metas verdes y evita los agujeros.", fiabilidad: 'oficial', kit: 'joystick-track', tamano: 'M', ola: 'E' },
  { id: "buho-calculador", num: 45, nombre: "Búho Calculador", emoji: "🦉", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 4.72, duracionSeg: 15, instrucciones: "Resuelve 5 operaciones eligiendo entre 4 respuestas. Cada fallo suma 1 s.", fiabilidad: 'video', kit: 'quiz-dom', tamano: 'S', ola: 'B' },
  { id: "zorro-de-los-dados", num: 46, nombre: "Zorro de los Dados", emoji: "🦊", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 3.46, duracionSeg: 15, instrucciones: "Aparecen 4 dados: escribe su suma en el teclado. Son 3 rondas.", fiabilidad: 'video', kit: 'quiz-dom', tamano: 'S', ola: 'B' },
  { id: "ardilla-contadora", num: 47, nombre: "Ardilla Contadora", emoji: "🐿️", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 2.29, duracionSeg: 15, instrucciones: "Toca los números del 1 al 16 en orden en una cuadrícula desordenada.", fiabilidad: 'video', kit: 'quiz-dom', tamano: 'S', ola: 'B' },
  { id: "cotorra-telefonista", num: 48, nombre: "Cotorra Telefonista", emoji: "🦜", categoria: 'velocidad', marcador: SPEC.segundosMenos, top1: 4.5, duracionSeg: 20, instrucciones: "Memoriza una secuencia de 8 dígitos y márcala en un teclado de colores.", fiabilidad: 'oficial', kit: 'quiz-dom', tamano: 'S', ola: 'B' },
  { id: "colibri-reflejos", num: 49, nombre: "Colibrí Reflejos", emoji: "🐦", categoria: 'velocidad', marcador: SPEC.segundos3, top1: 0.288, duracionSeg: 15, instrucciones: "En una cuadrícula de 3×3, un círculo se ilumina tras un tiempo aleatorio: tócalo lo antes posible. Son 3 rondas y cuenta la media.", fiabilidad: 'oficial', kit: 'reaction', tamano: 'S', ola: 'A' },
  { id: "trile-del-mapache", num: 50, nombre: "Trile del Mapache", emoji: "🦝", categoria: 'memoria', marcador: SPEC.niveles, top1: 13, duracionSeg: 60, instrucciones: "\"¡Mira la bola!\": el mapache mezcla 3 vasos y debes elegir dónde está la bola.", fiabilidad: 'oficial', kit: 'shuffle-anim', tamano: 'M', ola: 'B' },
  { id: "cuervo-contacajas", num: 51, nombre: "Cuervo Contacajas", emoji: "🪶", categoria: 'memoria', marcador: SPEC.niveles, top1: 19, duracionSeg: 60, instrucciones: "Aparece un montón de cajas un instante. Responde \"¿Cuántas cajas viste?\" con + y − y pulsa Enviar.", fiabilidad: 'oficial', kit: 'quiz-dom', tamano: 'M', ola: 'B' },
  { id: "chimpance-memorion", num: 52, nombre: "Chimpancé Memorión", emoji: "🐵", categoria: 'memoria', marcador: SPEC.puntos, top1: 100, duracionSeg: 60, instrucciones: "Los números se muestran boca arriba y luego se ocultan. Tócalos del primero al último antes de que se acabe el tiempo.", fiabilidad: 'oficial', kit: 'memory-grid', tamano: 'S', ola: 'B' },
  { id: "elefante-memorioso", num: 53, nombre: "Elefante Memorioso", emoji: "🐘", categoria: 'memoria', marcador: SPEC.puntos, top1: 100, duracionSeg: 90, instrucciones: "Observa la secuencia de flechas y, en \"Tu turno\", repítela con la cruceta. Cada ronda es más larga.", fiabilidad: 'oficial', kit: 'memory-seq', tamano: 'S', ola: 'B' },
  { id: "panal-de-la-abeja", num: 54, nombre: "Panal de la Abeja", emoji: "🐝", categoria: 'memoria', marcador: SPEC.puntos, top1: 148, duracionSeg: 60, instrucciones: "Se ilumina un patrón de celdas: reprodúcelo. La cuadrícula crece con cada nivel.", fiabilidad: 'video', kit: 'memory-grid', tamano: 'S', ola: 'B' },
  { id: "rastro-del-caracol", num: 55, nombre: "Rastro del Caracol", emoji: "🐌", categoria: 'memoria', marcador: SPEC.puntos, top1: 98, duracionSeg: 60, instrucciones: "Se muestra un recorrido entre puntos: repítelo trazándolo con el dedo.", fiabilidad: 'video', kit: 'trace', tamano: 'M', ola: 'B' },
  { id: "pulpo-camuflaje", num: 56, nombre: "Pulpo Camuflaje", emoji: "🐙", categoria: 'memoria', marcador: SPEC.parecido, top1: 99.18, duracionSeg: 40, instrucciones: "Memoriza un color y recréalo con las barras de tono, saturación y brillo.", fiabilidad: 'oficial', kit: 'color-match', tamano: 'S', ola: 'B' },
  { id: "loro-dictado", num: 57, nombre: "Loro Dictado", emoji: "🦜", categoria: 'memoria', marcador: SPEC.puntos, top1: 55, duracionSeg: 60, instrucciones: "Teclea los dígitos antes de que desaparezcan.", fiabilidad: 'oficial', kit: 'quiz-dom', tamano: 'S', ola: 'B' },
  { id: "burro-de-carga", num: 58, nombre: "Burro de Carga", emoji: "🐴", categoria: 'memoria', marcador: SPEC.puntos, top1: 41, duracionSeg: 60, instrucciones: "Empuja las cajas hasta los objetivos con la cruceta, sin dejarlas atrapadas.", fiabilidad: 'oficial', kit: 'sokoban', tamano: 'M', ola: 'B' },
  { id: "piton-pi", num: 59, nombre: "Pitón Pi", emoji: "🐍", categoria: 'memoria', marcador: SPEC.puntos, top1: null, duracionSeg: 60, instrucciones: "Teclea los decimales de π en orden. No hay botón de confirmar.", fiabilidad: 'sin confirmar', kit: 'quiz-dom', tamano: 'S', ola: 'B' },
  { id: "bingo-de-la-oveja", num: 60, nombre: "Bingo de la Oveja", emoji: "🐑", categoria: 'rapidez', marcador: SPEC.puntos, top1: 221, duracionSeg: 60, instrucciones: "Van saliendo bolas con números: toca las que coinciden con tu cartón. Tienes 3 vidas y tocar un número que no ha salido te quita una.", fiabilidad: 'video', kit: 'reaction', tamano: 'S', ola: 'A' },
  { id: "rinoceronte-rompemuros", num: 61, nombre: "Rinoceronte Rompemuros", emoji: "🦏", categoria: 'rapidez', marcador: SPEC.puntos, top1: 59, duracionSeg: 60, instrucciones: "Apunta y dispara bolas para romper los ladrillos numerados antes de que bajen.", fiabilidad: 'video', kit: 'brick-shooter', tamano: 'M', ola: 'D' },
  { id: "sepia-reflejos", num: 62, nombre: "Sepia Reflejos", emoji: "🦑", categoria: 'rapidez', marcador: SPEC.puntos, top1: 16, duracionSeg: 27, instrucciones: "Espera a que cambie el color de fondo y toca lo más rápido posible. Tocar antes de tiempo penaliza.", fiabilidad: 'oficial', kit: 'reaction', tamano: 'S', ola: 'A' },
  { id: "jardin-de-luciernagas", num: 63, nombre: "Jardín de Luciérnagas", emoji: "✨", categoria: 'rapidez', marcador: SPEC.puntos, top1: 129, duracionSeg: 60, instrucciones: "Caen luciérnagas: guía cada una hasta la flor de su color girando el haz de luz de luna.", fiabilidad: 'video+analisis', kit: 'deflect-guide', tamano: 'M', ola: 'D' },
  { id: "mariposa-pintora", num: 64, nombre: "Mariposa Pintora", emoji: "🦋", categoria: 'rapidez', marcador: SPEC.colores, top1: 32, duracionSeg: 60, instrucciones: "Iguala el color de la izquierda con el de la derecha lo más rápido posible usando las barras de tono y brillo.", fiabilidad: 'oficial', kit: 'color-match', tamano: 'S', ola: 'B' },
  { id: "ciguena-repartidora", num: 65, nombre: "Cigüeña Repartidora", emoji: "🦢", categoria: 'rapidez', marcador: SPEC.puntos, top1: 86, duracionSeg: 60, instrucciones: "Llegan paquetes por una cinta: con ←, ↑ y → manda cada uno al contenedor de su color.", fiabilidad: 'video', kit: 'reaction', tamano: 'S', ola: 'A' },
  { id: "gato-pianista", num: 66, nombre: "Gato Pianista", emoji: "🐱", categoria: 'rapidez', marcador: SPEC.puntos, top1: 157, duracionSeg: 60, instrucciones: "Toca las teclas que bajan sin tocar huecos vacíos.", fiabilidad: 'video', kit: 'tiles', tamano: 'S', ola: 'A' },
  { id: "oso-encestador", num: 67, nombre: "Oso Encestador", emoji: "🐻", categoria: 'rapidez', marcador: SPEC.canastas, top1: 33, duracionSeg: 60, instrucciones: "Toca para tirar a canasta. La primera canasta activa el reloj: sigue encestando antes de que llegue a cero.", fiabilidad: 'oficial', kit: 'aim-throw', tamano: 'M', ola: 'D' },
  { id: "pajaro-carpintero", num: 68, nombre: "Pájaro Carpintero", emoji: "🐤", categoria: 'rapidez', marcador: SPEC.toques, top1: 139, duracionSeg: 15, instrucciones: "Toca el tronco tantas veces como puedas en el tiempo del juego.", fiabilidad: 'oficial', kit: 'reaction', tamano: 'S', ola: 'A' },
  { id: "vencejo-veloz", num: 69, nombre: "Vencejo Veloz", emoji: "🐦", categoria: 'rapidez', marcador: SPEC.puntos, top1: 71, duracionSeg: 60, instrucciones: "Salen 4 casillas con flechas: desliza en su dirección antes de que se vacíe su barra.", fiabilidad: 'video', kit: 'reaction', tamano: 'S', ola: 'A' },
  { id: "golondrina-cazadora", num: 70, nombre: "Golondrina Cazadora", emoji: "🐦", categoria: 'rapidez', marcador: SPEC.puntos, top1: 731, duracionSeg: 60, instrucciones: "Toca los objetivos antes de que desaparezcan. Tienes 3 vidas.", fiabilidad: 'oficial', kit: 'reaction', tamano: 'S', ola: 'A' },
  { id: "cangrejo-interruptor", num: 71, nombre: "Cangrejo Interruptor", emoji: "🦀", categoria: 'rapidez', marcador: SPEC.puntos, top1: 73, duracionSeg: 60, instrucciones: "Aparecen interruptores por la pantalla: actívalos antes de que se vacíe la barra de tiempo.", fiabilidad: 'video', kit: 'reaction', tamano: 'S', ola: 'A' },
];
